n1 = input("Enter a First number: ")
n2 = input("Enter a Second number: ")
n3 = input("Enter a Third number: ")
sum = int(n1) + int(n2) + int(n3)
print(f"{n1} + {n2} + {n3} = {sum}")
dif = int(n1) - int(n2) - int(n3)
print(n1 + ' - ' + n2 + ' - ' + n3 + ' = ' + str(dif))